# Serial and Console
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# SPI OLED display
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y

# Keep the demo simple and predictable
CONFIG_MAIN_STACK_SIZE=2048
